routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \Spatie\Permission\Models\Role;
use \Spatie\Permission\Models\Permission;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// http://event.test/home
// http://event.test/login
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



// http://localhost:8000/users/index

	// Route::get('/users', 'UserController@index')
	//  					->name('users.index');


	// Route::get('/users', 'UserController@index')
	// 					->name('users.index');

	// Route::get('/users/create', 'UserController@create')
	// 					->name('users.create');

	// Route::get('/users/{user}', 'UserController@show')
	// 					->name('users.show');

	// Route::post('/users', 'UserController@store')
	// 					->name('users.store');

	// Route::get('/users/{user}/edit', 'UserController@edit')
	// 					->name('users.edit');

	// Route::put('/users/{user}', 'UserController@update')
	// 					->name('users.update');

	// Route::delete('/users/{user}', 'UserController@destroy')
// 					->name('users.destroy');
// http://localhost/welcome

//http://event.test/admin/states
Route::middleware(['auth'])
	// ->prefix('admin')
	// ->namespace('Admin')
	->group(function() {



	Route::resource('users','UserController');

	Route::resource('roles', 'RoleController');
	//Route::resource('users','StateController');
	//Route::get('welcome/{id}/{date?}', 'UserController@sayhi');

});

Route::get('/maklumat_pengguna/{user}', 'UserController@getdetail');

Route::get('/demo', 'StateController@demo');

Route::get('states/{state}/users', 'StateController@get_users')->name('states.users');

Route::get('states/{state}/pdf', 'StateController@export_pdf')->name('states.pdf');

Route::get('states/{state}/excel', 'StateController@export_excel')->name('states.excel');

Route::get('states/{state}/worksheet', 'StateController@export_multiplesheet')->name('states.export_multiplesheet');
Route::resource('states','StateController');

Route::get('/get_user', function() {
	return \DB::select("SELECT users.name as user_name, states.name as state_name, states.*, users.* 
						FROM users, states 
						WHERE  1=1
						AND users.state_id = states.id
						");

});

Route::get('/get_user2', function() {
	return \App\Model\State::with('users')->get();

});

Route::get('/test1', function() {
	//return App\Model\State::first()->kod;
	return App\Model\State::first();
});

Route::get('/test2', function() {

	$state = new App\Model\State();
	$state->name = "Pahang22";
	$state->kod = "Phg22";

	$state->save();

	$user = new App\User();
	$user->name = "abcde";
	$user->email = "fff@fefe.com";
	$user->password = \Hash::make('password');
	$user->state_id = $state->id;
	$user->save();
	//$state->users()->save($user);


	return $user;



});

Route::get('excelview', 'UserController@export_view')->name('users.excel.view');

Route::get('perm', function() {

 $admin = Role::where('name','admin')->first();
 $permission = Permission::where('name', 'manage user')->first();
 
 $admin->givePermissionTo($permission);

 $user = \App\User::first();
 $user->roles()->save($admin);

});

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\State;
use App\Http\Requests\State\Update;
use App\Http\Requests\State\Store;
use App\Exports\MultipleSheet;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $search = request()->search;
        //dapatkan data dari table state
        //$id = [1,2,4,6];
        $negeri2 = State::when($search, function($query) use ($search) {

                            $query->where(function($query) use ($search){
                                $query->where('name','LIKE', '%'. $search . '%')
                                      ->orWhere('kod','LIKE', '%'. $search . '%');
                            });
                        })
                        // ->orWhereHas('users', function($query) use ($search){
                        //         $query->where('name','LIKE', '%'. $search . '%')
                        //               ->orWhere('email','LIKE', '%'. $search . '%');
                        //     })
                        // ->with(['users'])
                        // ->whereYear('created_at', '2020')
                        ->orderBy('name','ASC')
                        //->whereIn('id',$id)
                        ->paginate(2);
        
        //gunakan view untuk papar data
        return view('state.index', [ 'negeri2' => $negeri2 ] );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('state.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Store $request)
    {
        
        //prepare row baru
        $state = new State();

        //dapatkan dan isi data
        $state->name = request()->name;
        $state->kod = request()->kod;

        //simpan data dalam db
        $state->save();

        session()->flash('notification', "Rekod updated");

        //redirect ke /states/index
        return redirect( route('states.index') );

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(State $state)
    {
        return view('state.show', [ 'negeri' => $state ] );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(State $state)
    {
        return view('state.edit', [ 'negeri' => $state ] );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Update $request, State $state)
    {
        
        //assign value baru
        $state->name = request()->name;
        $state->kod = request()->kod;
        //save
        $state->save();

        session()->flash('notification', "Rekod updated");

        //redirect ke index
        return redirect( route('states.index') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(State $state)
    {
        $state = State::find($id);
        $state->delete();

        session()->flash('notification', "Rekod deleted");

        return redirect( route('states.index') );
    }

    public function export_pdf(State $state) {

        $state->load('users');

        $pdf = \PDF::loadView('state.pdf', [ 'state' => $state ])
                                ->setPaper('a3', 'landscape')
        ;
        return $pdf->download( $state->name . '_' . date('Y-m-d') . '.pdf');
    }

    public function export_excel() {

        return \Excel::download(new \App\Exports\StateExport(), 
            'mystates.xlsx');
    }

    public function export_multiplesheet() {

        return \Excel::download(new MultipleSheet(), 
            'multiple.xlsx');
    }

    public function demo() {
      $states = State::get();
      return view('demo', compact('states'));  
    }

    public function get_users(State $state) {
        $state->load('users');
        return view('demo2', compact('state')) ;
    }

}

resources/views/state/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">

		<form action="{{ route('states.store') }}" method="POST">
			@csrf

		  <div class="form-group">
		    <label for="email">Kod</label>
		    <input type="text" class="form-control" id="kod" 
		    	name="kod"
		    	value="{{ old('kod') }}"
		    >
		    @error('kod')
		    	<span style="color:red;font-size:smaller;">
		    		{{ $message }}
		    	</span>
		    @enderror
		  </div>
		  <div class="form-group">
		    <label for="name">Name</label>
		    <input type="text" class="form-control" id="name"
		    	name="name"
		    	value="{{ old('name') }}"
		    >
		    @error('name')
		    	<span style="color:red;font-size:smaller;">
		    		{{ $message }}
		    	</span>
		    @enderror
		  </div>
		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
@endsection

resources/views/state/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">

		<form action="{{ route('states.update',[$negeri->id]) }}" method="POST">
			@csrf
			@method('PUT')
		  <div class="form-group">
		    <label for="name">Name</label>
		    <input type="text" class="form-control" id="name"
		    	name="name"
		    	value="{{ old('name', $negeri->name) }}"
		    >
		    @error('name')
		    	<span style="color:red;font-size:smaller;">
		    		{{ $message }}
		    	</span>
		    @enderror
		  </div>
		  <div class="form-group">
		    <label for="kod">Kod</label>
		    <input type="text" class="form-control" id="kod" 
		    	name="kod"
		    	value="{{ old('kod', $negeri->kod) }}"
		    	>
	    	@error('kod')
		    	<span style="color:red;font-size:smaller;">
		    		{{ $message }}
		    	</span>
	    	@enderror
		  </div>
		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>

	</div>
@endsection

@section('scripts')
<script src="{{ asset('js/datatable.js') }}" defer></script>

	<script type="text/javascript">
		alert('hello');
	</script>
@endsection

@section('styles')
<style type="text/css">
	h1 {
		color:red;
	}
</style>
@endsection

resources/views/state/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">

		<form method="GET" action="">
			<div class="form-group">
		    <label for="name">Name</label>
		    <input type="text" class="form-control" id="search"
		    	name="search"
		    	value="{{ request()->search }}"
		    >
		    <button class="btn btn-primary">Cari</button>
		  </div>
		</form>
		<table class="table table-striped">
			<tr>
				<th></th>
				<th>
					Kod
				</th>
				<th>
					Nama
				</th>
				<th>
					Total Users
				</th>
				<th>
					created At
				</th>
				<th></th>
			</tr>
			@foreach($negeri2 as $negeri)
				@if($loop->first
						&& (
						$negeri2->currentPage() == 1
						)
					)
				<tr>
					<td colspan="6">
						First Record
					</td>
				</tr>
				@endif
				<tr>
					<td>
						{{ $loop->iteration }}
					</td>
					<td> 
						{{ $negeri->kod }} 
					</td>
					<td>
						{{ $negeri->name_display }}
					</td>
					<td>
						{{ $negeri->users->count() }}
					</td>
					<td>
						{{ $negeri->created_at }}
					</td>
					<td>
						{{ $negeri->updated_at->format('d, M Y') }}
					</td>
					<td>
						<a class="btn btn-primary" href="{{ route('states.show',[$negeri->id]) }}">View</a>
						<a class="btn btn-primary" href="{{ route('states.pdf',[$negeri->id]) }}" target="_BLANK">Pdf</a>
						<a class="btn btn-primary" href="{{ route('states.edit',[$negeri->id]) }}">Edit</a>
						<a href="#" onclick="submit_form({{ $negeri->id }})"
							class="btn btn-warning"
							>Delete</a>
						<form action="{{ route('states.destroy',[$negeri->id]) }}" 
							method="POST" 
							id="del_{{ $negeri->id }}"
							> 
							@csrf
							@method('DELETE')
						</form>
					</td>
				</tr>
				@if($loop->last 
					&& (
						$negeri2->lastPage() == $negeri2->currentPage() 
						)
					)
				<tr>
					<td colspan="6">
						Last Record
					</td>
				</tr>
				@endif
			@endforeach
		</table>

		{{ $negeri2->appends(request()->input())->links() }}
	</div>

	<script>
		function submit_form(id) {
			if(confirm('Are you sure?')) {
				$('#del_' + id).submit();
			}
		}
	</script>
@endsection

resources/views/state/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>{{ $state->kod }} : {{ $state->name }}</h1>
	<h3>Users:</h3>
	<table style="width:100%;border:1px #000 solid;">
		@foreach($state->users as $user)
		<tr>
			<td>{{ $user->name }}</td>
			<td>{{ $user->email }}</td>
			<td>
				<a href="{{ route('users.show', [$user->id]) }}">View</a>
			</td>
		</tr>
		@endforeach
	</table>
</body>
</html>

resources/views/state/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		Kod: {{ $negeri->kod }} <br>
		Nama: {{ $negeri->name }}
	</div>
@endsection