routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \Spatie\Permission\Models\Role;
use \Spatie\Permission\Models\Permission;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// http://event.test/home
// http://event.test/login
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



// http://localhost:8000/users/index

	// Route::get('/users', 'UserController@index')
	//  					->name('users.index');


	// Route::get('/users', 'UserController@index')
	// 					->name('users.index');

	// Route::get('/users/create', 'UserController@create')
	// 					->name('users.create');

	// Route::get('/users/{user}', 'UserController@show')
	// 					->name('users.show');

	// Route::post('/users', 'UserController@store')
	// 					->name('users.store');

	// Route::get('/users/{user}/edit', 'UserController@edit')
	// 					->name('users.edit');

	// Route::put('/users/{user}', 'UserController@update')
	// 					->name('users.update');

	// Route::delete('/users/{user}', 'UserController@destroy')
// 					->name('users.destroy');
// http://localhost/welcome

//http://event.test/admin/states
Route::middleware(['auth'])
	// ->prefix('admin')
	// ->namespace('Admin')
	->group(function() {



	Route::resource('users','UserController');

	Route::resource('roles', 'RoleController');
	//Route::resource('users','StateController');
	//Route::get('welcome/{id}/{date?}', 'UserController@sayhi');

});

Route::get('/maklumat_pengguna/{user}', 'UserController@getdetail');

Route::get('/demo', 'StateController@demo');

Route::get('states/{state}/users', 'StateController@get_users')->name('states.users');

Route::get('states/{state}/pdf', 'StateController@export_pdf')->name('states.pdf');

Route::get('states/{state}/excel', 'StateController@export_excel')->name('states.excel');

Route::get('states/{state}/worksheet', 'StateController@export_multiplesheet')->name('states.export_multiplesheet');
Route::resource('states','StateController');

Route::get('/get_user', function() {
	return \DB::select("SELECT users.name as user_name, states.name as state_name, states.*, users.* 
						FROM users, states 
						WHERE  1=1
						AND users.state_id = states.id
						");

});

Route::get('/get_user2', function() {
	return \App\Model\State::with('users')->get();

});

Route::get('/test1', function() {
	//return App\Model\State::first()->kod;
	return App\Model\State::first();
});

Route::get('/test2', function() {

	$state = new App\Model\State();
	$state->name = "Pahang22";
	$state->kod = "Phg22";

	$state->save();

	$user = new App\User();
	$user->name = "abcde";
	$user->email = "fff@fefe.com";
	$user->password = \Hash::make('password');
	$user->state_id = $state->id;
	$user->save();
	//$state->users()->save($user);


	return $user;



});

Route::get('excelview', 'UserController@export_view')->name('users.excel.view');

Route::get('perm', function() {

 $admin = Role::where('name','admin')->first();
 $permission = Permission::where('name', 'manage user')->first();
 
 $admin->givePermissionTo($permission);

 $user = \App\User::first();
 $user->roles()->save($admin);

});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use \Spatie\Permission\Models\Role;
use \Spatie\Permission\Models\Permission;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::orderBy('name')->get();

        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::orderBy('name')->get();

        return view('roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $role_data['name'] = $request->name;
        $role_data['guard_name'] = 'web';
        $role = Role::create($role_data);

        if(!empty($request->permissions)) {
            $permissions = Permission::whereIn('id', $request->permissions)->get();
            $role->syncPermissions($permissions);
        }

        return redirect(route('roles.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::orderBy('name')->get();

        return view('roles.edit', compact('role','permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {

        $role->name = $request->name;
        $role->save();

        if(!empty($request->permissions)) {
            $permissions = Permission::whereIn('id', $request->permissions)->get();
            $role->syncPermissions($permissions);
        }

        return redirect(route('roles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();

        return redirect(route('roles.index'));
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
	<div class="card-body">
		<a href="{{ url('/roles') }}" class="btn btn-outline-primary btn-xs"><i class="fa fa-angle-double-left fa-sm" ></i>{{ __('Kembali') }}</a><p></p>
		<ul class="nav nav-tabs nav-tabs-highlight">
			<li class="nav-item"><a href="#left-icon-tab1" class="nav-link active" data-toggle="tab"><i class="icon-menu7 mr-2"></i>{{ __('Tambah Role') }}</a></li>
		</ul>

	<div class="tab-content">
	<div class="tab-pane fade show active" id="left-icon-tab1">

    <div class="card-body">
        <form action="{{ route('roles.store') }}" method='POST'>
            @csrf
            <div class="form-group row">
                <label class="col-form-label col-lg-2">{{ __('Nama Role') }}</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" name="name" value="{{ old('name')}}" required>
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
				Pilih Modul dibenarkan
                <table class="table table-hover">
					<thead>
                    <tr class="bg-grey-400">
                        <th>{{ __('Permission') }}</th>
                        <th>{{ __('Description') }}</th>
                        <th>{{ __('Tindakan') }}</th>
                    </tr>
					</thead>
                    @foreach($permissions as $permission)
                        <tr>
                            <td>{{ $permission->name }}</td>
                            <td>{{ $permission->description }}</td>
                            <td class="text-center ">
                                <input type="checkbox"
                                       name="permissions[{{ $permission->id }}]"
                                       value="{{ $permission->id }}"
                                        @if(old('permissions['. $permission->id.']') == $permission->id)
                                            checked="checked"
                                        @endif
                                >
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
            </div>
        </form>
    </div>

</div></div></div></div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
	<div class="card-body">
		<a href="{{ url('/roles') }}" class="btn btn-outline-primary btn-xs"><i class="fa fa-angle-double-left fa-sm" ></i>{{ __('Kembali') }}</a><p></p>
		<ul class="nav nav-tabs nav-tabs-highlight">
			<li class="nav-item"><a href="#left-icon-tab1" class="nav-link active" data-toggle="tab"><i class="icon-menu7 mr-2"></i>{{ __('Kemaskini Role') }}</a></li>
		</ul>

	<div class="tab-content">
	<div class="tab-pane fade show active" id="left-icon-tab1">

    <div class="card-body">
        <form action="{{ route('roles.update', $role->id) }}" method='POST'>
            @csrf
            @method('PUT')

            <div class="form-group row">
                <label class="col-form-label col-lg-2">{{ __('Nama') }}</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" name="name" value="{{ (old('name'))? old('name') : $role->name }}" required>
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <table class="table table-hover">
                   <thead>
                    <tr class="bg-grey-400">
                        <th>{{ __('Permission') }}</th>
                        <th>{{ __('Description') }}</th>
                        <th>{{ __('Tindakan') }}</th>
                    </tr>
					</thead>
                    <?php
                        $cur_permissions = $role->permissions->pluck('id')->toArray();
                    ?>
                    @foreach($permissions as $permission)
                        <tr>
                            <td>{{ $permission->name }}</td>
                            <td>{{ $permission->description }}</td>
                            <td class="text-center ">
                                <input type="checkbox"
                                       name="permissions[{{ $permission->id }}]"
                                       value="{{ $permission->id }}"
                                       @if(
                                       (old('permissions['. $permission->id.']') == $permission->id)
                                        || ( in_array($permission->id, $cur_permissions) )
                                        )
                                       checked="checked"
                                    @endif
                                >
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
            </div>
        </form>
    </div>

</div></div></div></div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="card">
		<div class="card-header header-elements-inline bg-green">
			<h5 class="card-title font-weight-semibold">{{ __('Senarai Role') }}</h5>
			<div class="header-elements">
				<div class="list-icons">
					<a class="list-icons-item" data-action="collapse"></a>
				</div>
			</div>
		</div>

		<div class="card-header bg-transparent header-element-inline">
			<div class="header-elements">
				<div class="text-right">
					<a href="{{ route('roles.create') }}" class="list-icon-items btn btn-primary btn-sm"><i class="icon-add"></i> {{__('Tambah Role')}}</a>
				</div>
			</div>
		</div>

        <div class="table-responsive">
            <table class="table table-hover">
				<thead>
					<tr class="bg-grey-300">
						<th>#</th>
						<th>
							<span class="font-weight-semibold">{{ __('Role') }} <a href="{{ route('roles.create') }}"><i class="icon-plus-circle2"></i></a></span>
							<i class="icon-plus ml-2"></i>
						</th>
						<th>Tindakan</th>
					</tr>
				</thead>
                <tbody>
				@php $bil = 1;@endphp
                @foreach($roles as $role)
                    <tr>
                        <td>{{ $bil++ }}</td>
                        <td>{{ $role->name }}</td>
                        <td>
                            <a href="{{ route('roles.edit' , $role->id )}}" class='btn btn-primary'><i class="icon-pencil"></i></a>
                            <a href="#" class='btn btn-danger' onclick="mform.delete({{ $role->id }}, 'del_{{ $role->id }}', '{{ __('Anda pasti?') }}' )"><i class="fa fa-trash-alt"></i></a>
                            <form action="{{ route('roles.destroy' , $role->id )}}" method="POST" id="del_{{ $role->id }}">
                                @csrf
                                @method('delete')
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('script')
    function delete_rec(id) {

    }
@endsection